// frontend/src/components/event/EventButton.tsx
import { images } from "./../../constants";

interface iEventButton {
  btnCss?: string;
  btnImage?: {
    icon: string;
    altText: string;
    imgCss: string;
  };
  processing?: boolean;
  btnTxt?: string;
  handleOnClick: () => void;
}

export default function EventButton({
  btnCss,
  btnImage,
  btnTxt,
  processing,
  handleOnClick,
}: iEventButton) {
  return (
    <>
      <button onClick={() => handleOnClick()} className={btnCss}>
        {btnImage ? (
          <img
            src={btnImage.icon}
            alt={btnImage.altText}
            className={btnImage.imgCss}
          />
        ) : (
          ""
        )}
        {processing ? (
          <img src={images.processingGif} alt="Processing Gif" width="20" />
        ) : btnTxt ? (
          btnTxt
        ) : (
          ""
        )}
      </button>
    </>
  );
}

// frontend_vue/src/components/events/EventButton.vue
<template>
  <button :class="btnCss">
    <template v-if="btnImage">
      <img :src="btnImage.icon" :alt="btnImage.altText" :class="btnImage.imgCss" />
    </template>
    <img
      v-if="processing"
      :src="images.processingGif"
      alt="Processing Gif"
      width="20"
    />
    {{ btnTxt }}
  </button>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-facing-decorator";
import { images } from "./../../constants";
@Component({
  name: "EventButtons",
})
export default class EventButton extends Vue {
  @Prop
  btnCss: string;
  @Prop
  btnImage: string;
  @Prop
  btnTxt: string;
  @Prop
  processing: string;
}
</script>
